name: Scorecard
on:
  push: { branches: [main] }
  schedule: [{ cron: "0 6 * * 1" }]
permissions: read-all
jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions: { security-events: write, actions: read, contents: read }
    steps:
      - uses: ossf/scorecard-action@af76153369ae1eb1eaffc4118046b7fda9a8419e
        with: { results_file: results.sarif, results_format: sarif }
      - if: always()
        uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: results.sarif }
